use_frameworks!

platform :ios, '10.0'

target 'milan2056_Example' do
  pod 'milan2056', :path => '../'

  target 'milan2056_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
